### ISSUE TITLE
Web timeout for restore

### ISSUE THREAD

**Issue by bukowski12** [bacularis/bacularis-web#3]
Please what variable increase

[Thu Dec 15 09:35:37.380641 2022] [proxy_fcgi:error] [pid 221112:tid 140124440487680] (70007)The timeout specified has expired: [client 192.168.16.220:50766] AH01075: Error dispatching request to :9097: (polling), referer: http://backup.example.cz:9097/web/restore/
[Thu Dec 15 09:35:37.559491 2022] [proxy_fcgi:error] [pid 221112:tid 140124306269952] (70007)The timeout specified has expired: [client 127.0.0.1:54760] AH01075: Error dispatching request to :9097: (polling)

**Comment by ganiuszka** [comment]
Hello @bukowski12 

Thanks for your question about the timeout. I would propose to add in the Apache Bacularis virtual host config the following directives with this value (10 minutes):

```
FcgidIdleTimeout 600
FcgidProcessLifeTime 600
FcgidConnectTimeout 600
FcgidIOTimeout 600
Timeout 600
ProxyTimeout 600
```

Apache Bacularis virtual host config usually you can find here:

For RPMS:
```
/etc/httpd/conf.d/bacularis.conf
```

For DEBS:
```
/etc/apache2/sites-available/bacularis.conf
```

To make it working you will also need to increase maximum execution time for PHP scripts. It is in php.ini config file:

```
max_execution_time = 600
```

PHP configuration file usually you can find in:

For RPMS:
```
/etc/php.ini
```

For DEBS (PHP 7.4)
```
/etc/php/7.3/fpm/php.ini
```

Please also note that for AJAX requests on the Bacularis client side there is a timeout set in the PRADO framework. If you have a problem with long asynchronous requests, it might be good to increase this value too. In file:

```
/usr/share/bacularis/protected/vendor/pradosoft/prado/framework/Web/Javascripts/source/prado/activecontrols/ajax3.js
```

you need to set (in miliseconds):

```
RequestTimeOut : 600000,
```

After this change please remember about refreshing the web browser cache.

At the end I would like to mention that sometimes it is better to reorganize FileSet and split it into more jobs than one. This way to restore we don't need to browse and process milions files that takes Bacula Director long time.

Good luck. Please let us know if it helped.

Best regards,
Marcin Haba (gani)

**Comment by bukowski12** [comment]
It works, thank you.

**Comment by ganiuszka** [comment]
Thank you for the confirmation.
