### ISSUE TITLE
VM full backup - Xen

### ISSUE THREAD

**Issue by pitman123** [bacularis/bacularis-web#4]
Hi! 

Does the free version of Bacula support backups of Xen Virtual Machines, and is this functionality also supported in the web application? I'm looking to understand the capabilities of the free version in relation to Xen VM backups, and whether the web interface provides the same functionality. Any insights or guidance would be greatly appreciated.

**Comment by ganiuszka** [comment]
Hello pitman123,

Unfortunately Bacula does not provide Xen plugin in the Community edition.

For the web interface, Bacularis supports defining plugins in the Plugin FileSet directives but the directives will work only when the plugins are loaded.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
I am closing this issue.
