### ISSUE TITLE
All files in /var/cache/baculatis have 777 permission

### ISSUE THREAD

**Issue by keestux** [bacularis/bacularis-web#6]
Installation is Ubuntu 22. Everything manually installed (well, through ansible).

The files created in `/var/cache/bacularis` all have `777` permission. That's not good practice.

**Comment by ganiuszka** [comment]
Hello @keestux,

Thank you for reporting this issue.

Yes, you are right, the permissions are incorrect. This is a bug that will be fixed quickly.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hello @keestux,

This bug has been fixed. Now the default asset file permissions are ``644``, and asset dir permissions are ``755``.

This change will be available in the next release.

After upgrading you can manually remove all content of the ``/var/cache/bacularis/`` and the assets will be re-created with correct permissions. We will also add appropriate information to the release notes about it.

Thank you!

Best regards,
Marcin Haba (gani)
