### ISSUE TITLE
Fatal Error when executing a backup job

### ISSUE THREAD

**Issue by satamazing** [bacularis/bacularis-web#8]
Hello, 

I have been following the YouTube Bacularis tutorial to perform some backups between servers and anytime I execute a job I get the same error. I tried with different client servers and always the same error. Pretty sure I am doing something wrong in my configuration.

Error: Fatal error: Socket error on Storage command: ERR=Interrupted system call

Bacularis Version: 4.3.0
Bacula Server OS: Debian 12
Bacula Clients OS I tried: Ubuntu Noble, Debian 12

How to reproduce: 

Create client, storage and job following instructions in Bacularis "Bacula for Everybody" series and execute the created job.
I had to cancel the jobs because it can be doing nothing for hours, then check the log

Job Log:

baculasrv-dir JobId 1: Bacula baculasrv-dir 9.6.7 (10Dec20):
  Build OS:               x86_64-pc-linux-gnu debian bookworm/sid
  JobId:                  1
  Job:                    [ZNodo1Test](http://192.168.99.32:9097/web/job/ZNodo1Test).2024-10-31_09.01.50_06
  Backup Level:           Full
  Client:                 "[znodo1-fd](http://192.168.99.32:9097/web/client/znodo1-fd)" 5.2.6 (21Feb12) x86_64-pc-linux-gnu,debian,7.0
  FileSet:                "[ZNodo1 Test](http://192.168.99.32:9097/web/fileset/ZNodo1%20Test)" 2024-10-31 09:01:50
  Pool:                   "[File](http://192.168.99.32:9097/web/pool/File)" (From Command input)
  Catalog:                "MyCatalog" (From Client resource)
  Storage:                "[ZNodo1Autochanger](http://192.168.99.32:9097/web/storage/ZNodo1Autochanger)" (From Command input)
  Scheduled time:         31-oct-2024 09:01:50
  Start time:             31-oct-2024 09:01:52
  End time:               31-oct-2024 09:02:13
  Elapsed time:           21 secs
  Priority:               10
  FD Files Written:       0
  SD Files Written:       0
  FD Bytes Written:       0 (0 B)
  SD Bytes Written:       0 (0 B)
  Rate:                   0.0 KB/s
  Software Compression:   None
  Comm Line Compression:  None
  Snapshot/VSS:           no
  Encryption:             no
  Accurate:               no
  Volume name(s):         
  Volume Session Id:      1
  Volume Session Time:    1730361250
  Last Volume Bytes:      0 (0 B)
  Non-fatal FD errors:    1
  SD Errors:              0
  FD termination status:  Canceled
  SD termination status:  Canceled
  Termination:            Backup Canceled
baculasrv-dir JobId 1: Fatal error: Socket error on Storage command: ERR=Interrupted system call
baculasrv-dir JobId 1: Using Device "ZNodo1Autochanger-001" to write.
baculasrv-dir JobId 1: Created new Volume="Vol-0001", Pool="File", MediaType="FileVol" in catalog.
baculasrv-dir JobId 1: Start Backup JobId 1, Job=ZNodo1Test.2024-10-31_09.01.50_06

Thank you so much.

Best regards

**Comment by satamazing** [comment]
Hello, 

A little update.

After leaving the job for more time I got this errors in the log:

znodo1-fd JobId 2: Fatal error: bsock.c:133 Unable to connect to Storage daemon on 192.168.99.201:9103. ERR=Connection refused
znodo1-fd JobId 2: Warning: bsock.c:127 Could not connect to Storage daemon on 192.168.99.201:9103. ERR=Connection refused
Retrying ...
znodo1-fd JobId 2: Warning: bsock.c:127 Could not connect to Storage daemon on 192.168.99.201:9103. ERR=Connection refused
Retrying ...
znodo1-fd JobId 2: Warning: bsock.c:127 Could not connect to Storage daemon on 192.168.99.201:9103. ERR=Connection refused
Retrying ...
znodo1-fd JobId 2: Warning: bsock.c:127 Could not connect to Storage daemon on 192.168.99.201:9103. ERR=Connection refused
Retrying ...
znodo1-fd JobId 2: Warning: bsock.c:127 Could not connect to Storage daemon on 192.168.99.201:9103. ERR=Connection refused
Retrying ...
znodo1-fd JobId 2: Warning: bsock.c:127 Could not connect to Storage daemon on 192.168.99.201:9103. ERR=Connection refused
Retrying ...

**Comment by ganiuszka** [comment]
Hello @satamazing,

Thanks for providing all details.

For this error I would propose to check the connection between Bacula Client and Bacula Storage Daemon (FD => SD). You can for example to log in to the FD host and run:

```
telnet 192.168.99.201 9103
```

This way you will see if the connection is possible to establish at all. Maybe it is a matter or firewall or something other what causes that the FD is not able to connect to SD.

Best regards,
Marcin Haba (gani)

**Comment by satamazing** [comment]
Hello @ganiuszka 

I get this result in the telnet (I use no firewall for testing):

root@baculasrv:/# telnet 192.168.99.201 9103
Trying 192.168.99.201...
Connected to 192.168.99.201.
Escape character is '^]'.

I have been researching myself and found out it could be problem of the bacula-sd.conf service and it was not configured. So I configured it manually and now get this other errors:

Termination:            *** Backup Error ***
baculasrv-dir JobId 5: Fatal error: Bad response to Storage command: wanted 2000 OK storage
, got 2902 Bad storage
znodo1-fd JobId 5: Fatal error: Failed to authenticate Storage daemon.
znodo1-fd JobId 5: Fatal error: Authorization key rejected by Storage daemon.
Please see http://www.bacula.org/en/rel-manual/Bacula_Freque_Asked_Questi.html#SECTION003760000000000000000 for help.
baculasrv-dir JobId 5: Using Device "ZNodo1Autochanger-001" to write.
baculasrv-dir JobId 5: Start Backup JobId 5, Job=ZNodo1Test.2024-10-31_09.59.28_49

I checked twice and the password and services name are ok...

Thanks so much for the help here.

Regards

Julen @satamazing

**Comment by ganiuszka** [comment]
Hello @satamazing,

OK, I see Thanks.

I meant running the telnet on the znodo1 host, not on baculasrv host. Are they the same host or they are different?

For this errors after changes in configuration, I would also propose to make sure that after all changes the configuration is reloaded (SD is restarted and Director is reloaded in Bconsole).

Best regards,
Marcin Haba (gani)

**Comment by satamazing** [comment]
hello @ganiuszka 

From the client to the server there is an issue for sure:

mad:/home1/_locals/operator# telnet 192.168.99.32 9103
Trying 192.168.99.32...
telnet: Unable to connect to remote host: Connection refused

They are in different machines but same local network

I will try reloading the services

Thanks a lot

Julen @satamazing

**Comment by ganiuszka** [comment]
Hello Julen (@satamazing)

I hope you were able to fix this problem.

The telnet output shows that there is an error in connection to that host on port 9103. It seems to be a problem on lower layer than Bacularis (Bacula, operating system, ...etc.)

If you will have any additional information, please let us know. For now I am closing this issue.

Best regards,
Marcin Haba (gani)

**Comment by satamazing** [comment]
Hello, 

I have not been able to fix this. I am new in Bacula and don´t know what I could be doing wrong.

By default the Bacularis Server servicies were listening only for 127.0.0.1 conections and that was the reason I couldnt telnet from the client. I removed the field so now listens in 0.0.0.0 (confirmed with netstat) and I can telnet in both directions to all ports with no issues... however I still get error when launching a job:

baculasrv-dir JobId 6: Start Backup JobId 6, Job=UTST.2024-11-05_09.23.51_17
baculasrv-dir JobId 6: Using Device "UTST-001" to write.
baculasrv-dir JobId 6: Fatal error: Socket error on Storage command: ERR=Llamada al sistema interrumpida
baculasrv-dir JobId 6: Bacula baculasrv-dir 9.6.7 (10Dec20):
  Build OS:               x86_64-pc-linux-gnu debian bookworm/sid
  JobId:                  6
  Job:                    [UTST](http://192.168.99.23:9097/web/job/UTST).2024-11-05_09.23.51_17
  Backup Level:           Full
  Client:                 "[192.168.99.166-fd](http://192.168.99.23:9097/web/client/192.168.99.166-fd)" 13.0.4 (12Feb24) x86_64-pc-linux-gnu,ubuntu,24.04
  FileSet:                "[UTST](http://192.168.99.23:9097/web/fileset/UTST)" 2024-11-04 14:55:37
  Pool:                   "[File](http://192.168.99.23:9097/web/pool/File)" (From Command input)
  Catalog:                "MyCatalog" (From Client resource)
  Storage:                "[UTST](http://192.168.99.23:9097/web/storage/UTST)" (From Command input)
  Scheduled time:         05-nov-2024 09:23:51
  Start time:             05-nov-2024 09:23:53
  End time:               05-nov-2024 09:30:14
  Elapsed time:           6 mins 21 secs
  Priority:               10
  FD Files Written:       0
  SD Files Written:       0
  FD Bytes Written:       0 (0 B)
  SD Bytes Written:       0 (0 B)
  Rate:                   0.0 KB/s
  Software Compression:   None
  Comm Line Compression:  None
  Snapshot/VSS:           no
  Encryption:             no
  Accurate:               no
  Volume name(s):         
  Volume Session Id:      1
  Volume Session Time:    1730794921
  Last Volume Bytes:      0 (0 B)
  Non-fatal FD errors:    1
  SD Errors:              0
  FD termination status:  Canceled
  SD termination status:  Canceled
  Termination:            Backup Canceled
  
Im very lost here.
Best regards

**Comment by ganiuszka** [comment]
Hello Julen (@satamazing),

OK, no problem.

This looks to be a strange problem.

Could you show us the ``UTST`` storage configuration on the Bacula Director side (Storage resource)?

Also could you tell us what is version of the Bacula Storage Daemon?

Thanks.

Best regards,
Marcin Haba (gani)

**Comment by satamazing** [comment]
Hi @ganiuszka 

Thanks so much for the help

This is the UTST configuration in Bacula Director:

![imagen](https://github.com/user-attachments/assets/6718161e-a624-482b-89d1-083b9589e493)

This is the version of the Bacula installed in the server. The client was deployed with the deployment tool form the Server

![imagen](https://github.com/user-attachments/assets/35c9e551-470e-4b7e-a2cc-9bc74d509356)

I have checked all the passwords and names of the different services and it seems ok to me

Let me know if you need some more info

Regards

Julen

**Comment by ganiuszka** [comment]
Hello Julen (@satamazing),

OK, I see what is wrong. Two things to change:

1) The 127.0.0.1 address should be changed to an address that is accessible for all Bacula clients. This address in the Storage resource in Director config during backup is sent to the file daemon and file daemon is trying to connect with the storage daemon on 127.0.0.1. But for the file daemon this 127.0.0.1 means something different than for the storage daemon. I mean that the file daemon looks for the storage daemon on its local host instead of on the storage daemon host.

2) The director and the storage daemon versions are older than the file daemon. The general rule for the compatibility between Bacula component versions is that director should be in the same version as storage daemon. The file daemon version can be older or equal the storage daemon and director version. So, the rule is:

(DIR == SD) >= FD

In case newer file daemon than the storage daemon/director, there is a chance that it can work but it isn't guaranteed, specially if between these versions are done some changes in the communcation protocol.

In this case I would suggest to upgrade the DIR/SD or downgrade the FD.

Good luck!

Best regards,
Marcin Haba (gani)

**Comment by satamazing** [comment]
Hi @ganiuszka 

I'm a bit confused. Excuse my lack of knowledge.

How do you know the director and storage daemon are older than the file daemon?. Looks like the same version to me.

I'm so sorry if this is a naive and basic question.

Regards

Julen

**Comment by ganiuszka** [comment]
Hi @satamazing,

Sure, don't worry. It is in the job log:

```
Client: "192.168.99.166-fd" 13.0.4 (12Feb24) x86_64-pc-linux-gnu,ubuntu,24.04
```

This ``13.0.4`` is the file daemon version.

Best regards,
Marcin Haba (gani)

**Comment by satamazing** [comment]
Hi @ganiuszka 

I had so many problems to downgrade the Ubuntu 24.04 bacula files so I decided to install Debian 12 in the client test server. Is the same OS installed in the bacula server so there should be full compatibility but I face a new issue now:

When using deployment tool to install bacula and bacularis in the new client (Debian 12) and press the test button nothing happens... the icon spins forever and the website gets frozen. Even reloading the nginx service does not fix it and the server has to be reloaded.

I tried a ssh connection from the server to the client and works fine.

![image](https://github.com/user-attachments/assets/d16b3f8f-2857-4584-b911-39dfb05cca4d)

How to replicate: Install Bacularis 4.3.0 in a Debian 12 server and try a deployment in an Debian 12 client

Best regards

Julen

**Comment by ganiuszka** [comment]
Hi Julen (@satamazing),

Thanks for reporting this problem.

Could I ask you about using this patch and telling me if it solves this problem with hanging?

[issue_8_fix_hanging_ssh_commands.patch.txt](https://github.com/user-attachments/files/17648579/issue_8_fix_hanging_ssh_commands.patch.txt)

To apply this patch, please copy it to this path on the host with the Bacularis web interface:

```
[BACULARIS_ROOT_DIRECTORY]/protected/vendor/bacularis/bacularis-web
```

Then please go to this path:

```
cd [BACULARIS_ROOT_DIRECTORY]/protected/vendor/bacularis/bacularis-web
```

and run the patch program in the following way:

```
patch -p1 < issue_8_fix_hanging_ssh_commands.patch.txt
```

Thanks in advance for letting us know if it helped.

Best regards,
Marcin Haba (gani)

**Comment by satamazing** [comment]
Hello @ganiuszka 

Once the patch was applied, it worked perfectly.

![image](https://github.com/user-attachments/assets/d7bfe6f7-7bee-40a7-ab27-26ee166f5f57)

Best regards, 
Julen

**Comment by ganiuszka** [comment]
Hi @satamazing,

Great. Many thanks for the test and confirmation.

This fix will be available in the next Bacularis release.

Best regarads,
Marcin Haba (gani)
